"""versao inicial

Revision ID: 0e069dded297
Revises: 
Create Date: 2026-07-29 14:20:24.021562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '0e069dded297'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_test', sa.Boolean(), nullable=False),
    sa.Column('balance', sa.Numeric(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_table('Team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player1_id', sa.Integer(), nullable=False),
    sa.Column('player2_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player1_id'], ['Player.id'], ),
    sa.ForeignKeyConstraint(['player2_id'], ['Player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_type', sa.Enum('SOLO', 'DOUBLES', name='matchtype'), nullable=False),
    sa.Column('team_a_id', sa.Integer(), nullable=False),
    sa.Column('team_b_id', sa.Integer(), nullable=False),
    sa.Column('winning_team_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'SCHEDULED', 'FINISHED', 'CANCELLED', name='matchstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_a_id'], ['Team.id'], ),
    sa.ForeignKeyConstraint(['team_b_id'], ['Team.id'], ),
    sa.ForeignKeyConstraint(['winning_team_id'], ['Team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Bet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('status', sa.Enum('WON', 'LOST', 'PENDING', 'REFUNDED', name='betstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['Match.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['Team.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Bet')
    op.drop_table('Match')
    op.drop_table('Team')
    op.drop_table('User')
    op.drop_table('Player')
    # ### end Alembic commands ###
