name: Python Application Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v7
        with:
          python-version: "3.13"

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v9.0.0
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --frozen --extra dev

      - name: Lint
        run: |
          uv run ruff check ./app --output-format=github

      - name: Test with pytest
        run: |
          uv run pytest
